FROM serversideup/php:8.4-fpm-nginx

# set some variables.
ENV FIREFLY_III_PATH=/var/www/html COMPOSER_ALLOW_SUPERUSER=1 DEBIAN_FRONTEND=noninteractive PHP_MAX_EXECUTION_TIME=300 PHP_ERROR_REPORTING=24575 SHOW_WELCOME_MESSAGE=false BASE_IMAGE_BUILD=296 BASE_IMAGE_DATE="27-04-2025 08:46:17 UTC" PHP_OPCACHE_ENABLE=1
LABEL build_version="5.1" maintainer="james@firefly-iii.org"

VOLUME $FIREFLY_III_PATH/storage/upload

COPY conf/locale.gen                     /etc/locale.gen
COPY scripts/wait-for-it.sh              /usr/local/bin/wait-for-it.sh
COPY scripts/finalize-image.sh           /usr/local/bin/finalize-image.sh
COPY scripts/execute-things-web.sh           /etc/entrypoint.d/11-execute-things.sh

USER root
RUN set -eux; \
    chmod uga+x /usr/local/bin/wait-for-it.sh && \
    chmod uga+x /usr/local/bin/finalize-image.sh && \
    apt update && apt install -y curl locales && \
    install-php-extensions intl
RUN set -eux;install-php-extensions bcmath 
RUN set -eux;install-php-extensions memcached 
RUN set -eux;install-php-extensions sockets 
RUN set -eux;rm -rf /var/lib/apt/lists/*

USER www-data
